embedding:
  model_name: all-MiniLM-L6-v2
  type: sentence_transformer
llm:
  model: gpt-4o-mini
  provider: openai
  temperature: 0.7
log_level: DEBUG
rag:
  rerank: true
  top_k: 5
vector_store:
  persist_directory: ./chroma_db_dev
  type: chromadb
